notifications:
  email: false

language: node_js
node_js:
  - "node"

sudo: false

install:
  - npm install

jobs:
  include:
    - stage: test
      script: npm run lint
    - stage: check
      script: npm audit
    - script: npm outdated
