notifications:
  email: false

language: node_js
node_js:
  - "node"

sudo: false

install:
  - npm install

jobs:
  include:
    - stage: test
      name: "Unit"
      script: npm test
    - name: "Lint"
      script: npm run lint
    - stage: check
      name: "Audit"
      script: npm audit
    - name: "Outdated"
      script: npm outdated
