name: Node.js Package

on:
  push:
    tags:
    - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm@next-7 && npm install
        name: Install Dependencies
      - run: echo -e 'registry=https://${REGISTRY_URL}\n//${REGISTRY_URL}:_authToken=${NODE_AUTH_TOKEN}' > .npmrc
        name: Configure Regisry
      - run: npm publish
        name: NPM Publish
        env:
          REGISTRY_URL: 'registry.npmjs.org/'
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: echo $(jq '.name = "@gfyoung/basic-tts"' package.json) > package.json && npm publish
        name: GitHub Publish
        env:
          REGISTRY_URL: 'npm.pkg.github.com/'
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
